### ISSUE TITLE
List Index out of range

### ISSUE THREAD

**Issue by melchiorcoi** [tcich/ha-addon-energa-meter#9]
Hej,
Dodałem dziś dodatek. Dodatek pobrał ostatnią wartość, chwilę potem musiałem restartować hosta HA (proxmoxa) mam błąd

[12:11:04] INFO: Uruchamiam API
2024-06-17 12:11:05,005 - energaMeter - INFO - Inicjalizacja OK.
2024-06-17 12:11:05,007 - waitress - INFO - Serving on http://0.0.0.0:8000
2024-06-17 12:11:05,018 - energaMeter - INFO - Rozpoczynam logowanie do Mój licznik.
2024-06-17 12:11:05,935 - energaMeter - INFO - Zalogowano
2024-06-17 12:11:05,937 - energaMeter - INFO - Licznik 123123 nie istnieje w systemie, zostanie dodany.
2024-06-17 12:11:05,955 - energaMeter - INFO - Aktualizacja liczników...
2024-06-17 12:11:06,316 - energaMeter - INFO - Zapisano stan licznika 123123 A+ taryfa 1 z dnia: 2024-06-17 00:00 : 000099999.3420
2024-06-17 12:11:06,316 - energaMeter - INFO - Wyszukiwanie najstarszych danych...(Może to trwać kilkadziesiąt minut.)
2024-06-17 12:11:13,334 - api - ERROR - Exception on /123123/A+/2 [GET]
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api.py", line 182, in get_countners
    countner = countners_result[0]
               ~~~~~~~~~~~~~~~~^^^
  File "/app/venv/lib/python3.12/site-packages/peewee.py", line 4486, in __getitem__
    return self.row_cache[item]
           ~~~~~~~~~~~~~~^^^^^^
IndexError: list index out of range

**Comment by paki111** [comment]
Działa czy jeszcze masz ten problem?

**Comment by melchiorcoi** [comment]
ciągle tak samo. działą podsumowanie ile energii (chociaż nie umiem zrobić dobrego dashboardu pokazującego jak na stronie energii dla 2 stref, żeby widzieć ile w dzięń strefy 1, ile drugiej), natomiast godzinowe info prawie od razu się wywala

**Comment by tcich** [comment]
numer licznika 123123 wydaje się błędny

**Comment by melchiorcoi** [comment]
> numer licznika 123123 wydaje się błędny

podmieniłem na taki przed wrzuceniem logu tutaj.
Generalnie nadal ma duży problem z zapisaniem historycznych stanów, zużycia, w miarę działa pobranie ostatniego stanu (sprzed doby)
